### ISSUE TITLE
Buttons not showing

### ISSUE THREAD

**Issue by hasib-rashid** [Nuggies-bot/nuggies-npm#24]
**The Buttons of Discord are not showing in Embed**

Hey there. I was playing around with this package and this ashtonished me. But i have a problem which is that the buttons of the embed are not showing. Here is a quick screenshot

![image](https://user-images.githubusercontent.com/69360193/125328812-91f73a00-e366-11eb-8245-033c3de9294c.png)

**Expected behavior**
The buttons are supposed to show here in the embed

**Screenshots**
![image](https://user-images.githubusercontent.com/69360193/125328874-a3404680-e366-11eb-96dd-e96eb420e195.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Package Version: 1.2.6
 - Node Version: 14

**Additional context**
Nothing else. Love the Package <3. Keep on the work

**Comment by Assassin-1234** [comment]
make sure you have `require(discord-buttons)(client)` after your client declaration, should fix it :)

**Comment by hasib-rashid** [comment]
Oh my god what a fast reply. Im sorry I saw this way before but i am still stuck. Anyways

Can you please like give a code snippet example. I stills cant get around it ;(

**Comment by Assassin-1234** [comment]
can you please show your index.js?

**Comment by Assassin-1234** [comment]
> Can you please like give a code snippet example. I stills cant get around it ;(
```js
const client = new Discord.Client();
require('discord-buttons')(client)
```

**Comment by hasib-rashid** [comment]
I dont know but i still dont see them :(

![image](https://user-images.githubusercontent.com/69360193/125333729-67a87b00-e36c-11eb-89b3-51c0de8f1049.png)

![image](https://user-images.githubusercontent.com/69360193/125333757-6d9e5c00-e36c-11eb-92ca-516cc7f31cb9.png)

**Comment by Assassin-1234** [comment]
are you using typescript?

**Comment by Assassin-1234** [comment]
afaik discord-buttons' typings dont work [check this out](https://github.com/discord-buttons/discord-buttons/issues/121)

**Comment by ChopChoP534** [comment]
```js
const client = new Discord.Client();
require('discord-buttons')(client)```
u need to add this in your main file(index.js, main.js, etc) and not in command file

**Comment by hasib-rashid** [comment]
Thank you all the buttons are now Showing. <3 Keep on the work. I have another issue in them though. Will I open another issue? or can we discuss just here?

**Comment by Assassin-1234** [comment]
we can just discuss it here :)

**Comment by hasib-rashid** [comment]
When I click on any of those buttons it shows this?
![image](https://user-images.githubusercontent.com/69360193/125383099-b5e36b80-e3b8-11eb-8e46-2b8201ec9533.png)

Sorry If I am being dumb :P

**Comment by Assassin-1234** [comment]
it doesn't, you have to handle the interactions by using 

```js
client.on('clickButton', button => {
	Nuggies.buttonclick(client, button);
});
```

**Comment by hasib-rashid** [comment]
Oh my god thank you so much excellent response time and service. Keep on the work :)
